const existing = Application.assets.find(asset => asset.id === Parameters.asset.id)
let accumulator = {}

const searchForValue = (tree, saveinBranch, page) => {
  tree.forEach(leaf => {
    if (leaf.type !== 'page') {
      if (leaf.values && (leaf.values.className || leaf.values.class)) {
        var foundClasses = leaf.values.className || leaf.values.class
        if (typeof foundClasses === 'string') foundClasses = [foundClasses]

        foundClasses.forEach(foundClass => {
          if (foundClass.substring(0,5) === 'theme') {
            var cleanClass = foundClass.substring(5)

            if (!saveinBranch[cleanClass]) saveinBranch[cleanClass] = { usedIn: [] }
            saveinBranch[cleanClass].usedIn.push(page.name)
            if (leaf.children && leaf.children.length) searchForValue(leaf.children, saveinBranch[cleanClass], page)
          }
        })
      } else {
        if (leaf.children && leaf.children.length) searchForValue(leaf.children, saveinBranch, page)
      }
    } else {
      searchForValue(leaf.children, saveinBranch, leaf )
    }
  })
  return accumulator
}

const convertObjectToSelectors = (tree, level = 0) => {
  let accumulator = ''
  Object.keys(tree).forEach(selector => {
    if (selector !== 'usedIn') {
      var usedInObject = tree[selector].usedIn.reduce((cnt, cur) => (cnt[cur] = cnt[cur] + 1 || 1, cnt), {})
      var usedInString = Object.keys(usedInObject).map(uio => {
        return usedInObject[uio] === 1 ? uio: `${uio}(${usedInObject[uio]} times)` 
      }).join(' ')
      let spaces = ''
      for (var I = 0; I < level; I++) spaces += '  '
      accumulator += `${spaces}${level > 0 ? '& ' : ''}${selector} { /* ${usedInString} */\n`
      accumulator += convertObjectToSelectors(tree[selector], level + 1)
      accumulator += `${spaces}}\n`
    }
  })
  return accumulator
}

let allSelectors = {}
aptugo.pageUtils.pages.forEach(page => {
  searchForValue(page.children, accumulator, page)
})

console.log('accumulator', accumulator)
let mainAccumulator = `/* Auto generated by Aptugo on ${Date().toLocaleString()} */\n\n`
mainAccumulator += convertObjectToSelectors(accumulator)
console.log(mainAccumulator)

if ( window.sendAptugoCommand ) {
    window.sendAptugoCommand({
        section: 'assets',
        command: 'setfile',
        options: `--app ${Application.settings.name} --id '${Parameters.asset.id}' --filename '${existing.name}'`,
        file: JSON.stringify(mainAccumulator)
    }).then(res => {
        console.log('Selectors Created')
    })
}

return Application